=== martinmontesjavier/martinmontesjavier.github.io/cinesllefia/esquema_cinesllefia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="peliculas">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="pelicula" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nombre">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="255"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="portada">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="255"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="trailer" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="255"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="valoracion">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="5"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="voto">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="1000000"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="clasificacion">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="255"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="duracion">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="500"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="paises">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="pais" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="255"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="generos">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="genero" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="255"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="estreno">
								<xs:complexType>
									<xs:attribute name="fecha" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:date">
												<xs:minInclusive value="2010-01-01"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="directores">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="director" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="255"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="guionistas">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="guionista" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="255"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="productores">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="productor" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="255"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="actores">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="actor" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="255"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="sinopsis">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="parrafo" maxOccurs="unbounded">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="255"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== martinmontesjavier/martinmontesjavier.github.io/cinesllefia/cinesllefia.xml
<?xml version="1.0" encoding="UTF-8"?>
<peliculas xsi:noNamespaceSchemaLocation="esquema_cinesllefia.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <pelicula>
        <nombre>No te preocupes querida</nombre>
        <portada>notepreocupesquerida.jpg</portada>
        <trailer>https://youtu.be/kMwLgSTNxb8</trailer>
        <valoracion>4</valoracion>
        <voto>165</voto>
        <clasificacion>PENDIENTE DE CALIFICACION</clasificacion>
        <duracion>122</duracion>
        <paises>
            <pais>Estados Unidos</pais>
        </paises>
        <generos>
            <genero>Drama</genero>
            <genero>Misterio</genero>
            <genero>Suspense</genero>
        </generos>
        <estreno fecha="2022-09-23"></estreno>
        <directores>
            <director>Brendan Lee</director>
            <director>Jonas Spaccarotelli</director>
            <director>Mark Anthony Little</director>
            <director>Michael Edward King</director>
            <director>Olivia Wilde</director>
        </directores>
        <guionistas>
            <guionista>Carey Van Dyke</guionista>
            <guionista>Katie Silberman</guionista>
            <guionista>Shane Van Dyke</guionista>
        </guionistas>
        <productores>
            <productor>New Line Cinema</productor>
            <productor>Vertigo Entertainment</productor>
        </productores>
        <actores>
            <actor>Chris Pine</actor>
            <actor>Florence Pugh</actor>
            <actor>Gemma Chan</actor>
            <actor>Harry Styles</actor>
            <actor>Kiki Layne</actor>
            <actor>Olivia Wilde</actor>
        </actores>
        <sinopsis>
            <parrafo>Centrado en la década de 1950, No te preocupes querida narra la historia de una pareja aparentemente feliz (interpretada por la actriz Florence Pugh y el cantante Harry Styles).</parrafo>
            <parrafo>en una apacible comunidad estadounidense, donde él trabaja para una gran coorporación, mientras ella es una abnegada ama de casa. </parrafo> 
            <parrafo>a poco, la preocupación de ella comienza a hacerse patente cuando empiece a descubrir detalles sobre el Proyecto Victoria, el trabajo que está desarrolando su marido. </parrafo> 
            <parrafo>el resto de mujeres de los empleados se dedican a ser discretas y sumisas, ella comienza a hacerse preguntas y a comprender horrorizada que su felicidad y su tranquila vida están más en peligro que nunca.</parrafo> 
        </sinopsis>
    </pelicula>

    <pelicula>
            <nombre>Spider-Man:No Way Home - The More Fun Stuff Version</nombre>
            <portada>spidermannowayhomethemorefunstuffversion.jpg</portada>
            <trailer>https://youtu.be/SkmRT3M4Vx4</trailer>
            <valoracion>4</valoracion>
            <voto>7017</voto>
            <clasificacion>No tiene</clasificacion>
            <duracion>160</duracion>
            <paises>
                <pais>Estados Unidos</pais>
            </paises>
            <generos>
                <genero>Ciencia ficción</genero>
                <genero>Acción</genero>
                <genero>Aventura</genero>
                <genero>Fantasía</genero>
            </generos>
            <estreno fecha="2022-09-23"></estreno>
            <directores>
                <director>Brian Avery Galligan</director>
                <director>David H. Venghaus Jr</director>
                <director>George Cottle</director>
                <director>Jon Watts</director>
            </directores>
            <guionistas>
                <guionista>Chris Mckenna</guionista>
                <guionista>Erik Sommers</guionista>
                <guionista>Stan Lee</guionista>
                <guionista>Steve Ditko</guionista>
            </guionistas>
            <productores>
                <productor>Sony Pictures</productor>
            </productores>
            <actores>
                <actor>Benedict Cumberbatch</actor>
                <actor>Jacob Batalon</actor>
                <actor>Jon Favreau</actor>
                <actor>Marisa Tomei</actor>
                <actor>Tom Holland</actor>
                <actor>Zendaya</actor>
            </actores>
            <sinopsis>
                <parrafo>Peter Parker está desenmascarado y ya no puede separar su vida normal de las altas apuestas de ser un superhéroe.</parrafo>
                <parrafo>Cuando le pide ayuda al Doctor Strange, lo que está en juego se vuelve aún más peligroso, lo que lo obliga a descubrir lo que realmente significa ser Spider-Man.</parrafo> 
            </sinopsis>
        </pelicula>

        <pelicula>
            <nombre>Crímenes del futuro</nombre>
            <portada>crmenesdelfuturo.jpg</portada>
            <trailer>https://youtu.be/LUu8JTMZTaE</trailer>
            <valoracion>4</valoracion>
            <voto>6</voto>
            <clasificacion>No tiene</clasificacion>
            <duracion>107</duracion>
            <paises>
                <pais>Canadá</pais>
            </paises>
            <generos>
                <genero>Drama</genero>
                <genero>Terror</genero>
                <genero>Ciencia ficción</genero>
            </generos>
            <estreno fecha="2022-09-23"></estreno>
            <directores>
                <director>David Cronenberg</director>
                <director>David Warry-smith</director>
                <director>Katerina Giannakopoulou</director>
                <director>Ken A. Smith</director>
                <director>Nefeli Rapti</director>
            </directores>
            <guionistas>
                <guionista>David Cronenberg</guionista>
            </guionistas>
            <productores>
                <productor>Argonauts Productions S.a.</productor>
                <productor>Bell Media Studios</productor>
                <productor>Cbc Films</productor>
                <productor>Ingenious Media</productor>
                <productor>Ontario Creates</productor>
                <productor> Rocketscience</productor>
                <productor>Serendipity Point Films</productor>
                <productor>Téléfilm Canada</productor>
            </productores>
            <actores>
                <actor>Don Mckellar</actor>
                <actor>Kristen Stewart</actor>
                <actor>Léa Seydoux</actor>
                <actor>Scott Speedman</actor>
                <actor>Viggo Mortensen</actor>
                <actor>Welket Bungué</actor>
            </actores>
            <sinopsis>
                <parrafo>Saul Tenser (Mortensen), célebre artista de performance, muestra públicamente la metamorfosis de sus órganos en actuaciones vanguardistas con su compañera Caprice (Seydoux). </parrafo>
                <parrafo>Timlin (Stewart), una investigadora del Registro Nacional de Órganos, sigue obsesivamente sus movimientos. Es entonces cuando un grupo misterioso aparece: Desean aprovechar la fama de Saul para revelar al mundo la próxima etapa de la evolución humana...</parrafo> 
            </sinopsis>
        </pelicula>

        <pelicula>
            <nombre>El grito silencioso. El caso Roe V.Wade</nombre>
            <portada>elgritosilenciosoelcasoroevwade.jpg</portada>
            <trailer>No tiene</trailer>
            <valoracion>4</valoracion>
            <voto>10</voto>
            <clasificacion>No tiene</clasificacion>
            <duracion>112</duracion>
            <paises>
                <pais>Estados Unidos</pais>
            </paises>
            <generos>
                <genero>Drama</genero>
                <genero>Historia</genero>
            </generos>
            <estreno fecha="2022-09-23"></estreno>
            <directores>
                <director>Cathy Allyn</director>
                <director>Nick Loeb</director>
            </directores>
            <guionistas>
                <guionista>Cathy Allyn</guionista>
                <guionista>Nick Loeb</guionista>
            </guionistas>
            <productores>
                <productor>Bcl Finance Group</productor>
                <productor>Smoke Shows y amp</productor>
                <productor>Clown Shows</productor>
            </productores>
            <actores>
                <actor>Jamie Kennedy</actor>
                <actor>Joey Lawrence</actor>
                <actor>Jon Voight</actor>
                <actor>Nick Loeb</actor>
                <actor>Robert Davi</actor>
                <actor>Stacey Dash</actor>
            </actores>
            <sinopsis>
                <parrafo>El Dr. Bernard Nathanson y la Dra. Mildred Jefferson se enfrentan en una batalla nacional en esta conspiración incalculable que condujo al caso judicial más famoso y controvertido de la historia.</parrafo>
            </sinopsis>
        </pelicula>

        <pelicula>
            <nombre>Los Buscamundos</nombre>
            <portada>losbuscamundos.jpg</portada>
            <trailer>https://youtu.be/nStlNg2Cr74</trailer>
            <valoracion>4</valoracion>
            <voto>26</voto>
            <clasificacion>No tiene</clasificacion>
            <duracion>82</duracion>
            <paises>
                <pais>Bélgica</pais>
                <pais>Francia</pais>
            </paises>
            <generos>
                <genero>Animación</genero>
                <genero>Aventura</genero>
                <genero>Familia</genero>
                <genero>Comedia</genero>
            </generos>
            <estreno fecha="2022-09-23"></estreno>
            <directores>
                <director>Samuel Tourneux</director>
            </directores>
            <guionistas>
                <guionista>David Michel</guionista>
                <guionista>Gerry Swallow</guionista>
